var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var schema = new Schema({ activeIngredient: { type: Schema.Types.ObjectId, ref: 'activeIngredient' },
  background: { type: Schema.Types.ObjectId, ref: 'background' },
  dosageForm: { type: Schema.Types.ObjectId, ref: 'dosageForm' },
  isProprietary: { type: Schema.Types.ObjectId, ref: 'isProprietary' },
  legalStatus: { type: Schema.Types.ObjectId, ref: 'legalStatus' },
  manufacturer: { type: Schema.Types.ObjectId, ref: 'manufacturer' },
  maximumIntake: { type: Schema.Types.ObjectId, ref: 'maximumIntake' },
  mechanismOfAction: { type: Schema.Types.ObjectId, ref: 'mechanismOfAction' },
  nonProprietaryName: { type: Schema.Types.ObjectId, ref: 'nonProprietaryName' },
  recommendedIntake: { type: Schema.Types.ObjectId, ref: 'recommendedIntake' },
  safetyConsideration: { type: Schema.Types.ObjectId, ref: 'safetyConsideration' },
  targetPopulation: { type: Schema.Types.ObjectId, ref: 'targetPopulation' },
  adverseOutcome: { type: Schema.Types.ObjectId, ref: 'adverseOutcome' },
  contraindication: { type: Schema.Types.ObjectId, ref: 'contraindication' },
  duplicateTherapy: { type: Schema.Types.ObjectId, ref: 'duplicateTherapy' },
  indication: { type: Schema.Types.ObjectId, ref: 'indication' },
  seriousAdverseOutcome: { type: Schema.Types.ObjectId, ref: 'seriousAdverseOutcome' },
  alternateName: { type: Schema.Types.ObjectId, ref: 'alternateName' },
  code: { type: Schema.Types.ObjectId, ref: 'code' },
  guideline: { type: Schema.Types.ObjectId, ref: 'guideline' },
  medicineSystem: { type: Schema.Types.ObjectId, ref: 'medicineSystem' },
  recognizingAuthority: { type: Schema.Types.ObjectId, ref: 'recognizingAuthority' },
  relevantSpecialty: { type: Schema.Types.ObjectId, ref: 'relevantSpecialty' },
  study: { type: Schema.Types.ObjectId, ref: 'study' },
  additionalType: { type: Schema.Types.ObjectId, ref: 'additionalType' },
  alternateName: { type: Schema.Types.ObjectId, ref: 'alternateName' },
  description: { type: Schema.Types.ObjectId, ref: 'description' },
  image: { type: Schema.Types.ObjectId, ref: 'image' },
  name: { type: Schema.Types.ObjectId, ref: 'name' },
  sameAs: { type: Schema.Types.ObjectId, ref: 'sameAs' },
  url: { type: Schema.Types.ObjectId, ref: 'url' },
  potentialAction: { type: Schema.Types.ObjectId, ref: 'potentialAction' } });
module.exports = mongoose.model('DietarySupplement', schema);