var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var schema = new Schema({ warning: { type: Schema.Types.ObjectId, ref: 'warning' },
  relatedDrug: { type: Schema.Types.ObjectId, ref: 'relatedDrug' },
  prescriptionStatus: { type: Schema.Types.ObjectId, ref: 'prescriptionStatus' },
  prescribingInfo: { type: Schema.Types.ObjectId, ref: 'prescribingInfo' },
  pregnancyWarning: { type: Schema.Types.ObjectId, ref: 'pregnancyWarning' },
  pregnancyCategory: { type: Schema.Types.ObjectId, ref: 'pregnancyCategory' },
  overdosage: { type: Schema.Types.ObjectId, ref: 'overdosage' },
  nonProprietaryName: { type: Schema.Types.ObjectId, ref: 'nonProprietaryName' },
  mechanismOfAction: { type: Schema.Types.ObjectId, ref: 'mechanismOfAction' },
  manufacturer: { type: Schema.Types.ObjectId, ref: 'manufacturer' },
  legalStatus: { type: Schema.Types.ObjectId, ref: 'legalStatus' },
  labelDetails: { type: Schema.Types.ObjectId, ref: 'labelDetails' },
  isProprietary: { type: Schema.Types.ObjectId, ref: 'isProprietary' },
  isAvailableGenerically: { type: Schema.Types.ObjectId, ref: 'isAvailableGenerically' },
  interactingDrug: { type: Schema.Types.ObjectId, ref: 'interactingDrug' },
  foodWarning: { type: Schema.Types.ObjectId, ref: 'foodWarning' },
  drugClass: { type: Schema.Types.ObjectId, ref: 'drugClass' },
  doseSchedule: { type: Schema.Types.ObjectId, ref: 'doseSchedule' },
  dosageForm: { type: Schema.Types.ObjectId, ref: 'dosageForm' },
  cost: { type: Schema.Types.ObjectId, ref: 'cost' },
  clincalPharmacology: { type: Schema.Types.ObjectId, ref: 'clincalPharmacology' },
  breastfeedingWarning: { type: Schema.Types.ObjectId, ref: 'breastfeedingWarning' },
  availableStrength: { type: Schema.Types.ObjectId, ref: 'availableStrength' },
  alcoholWarning: { type: Schema.Types.ObjectId, ref: 'alcoholWarning' },
  administrationRoute: { type: Schema.Types.ObjectId, ref: 'administrationRoute' },
  activeIngredient: { type: Schema.Types.ObjectId, ref: 'activeIngredient' },
  seriousAdverseOutcome: { type: Schema.Types.ObjectId, ref: 'seriousAdverseOutcome' },
  indication: { type: Schema.Types.ObjectId, ref: 'indication' },
  duplicateTherapy: { type: Schema.Types.ObjectId, ref: 'duplicateTherapy' },
  contraindication: { type: Schema.Types.ObjectId, ref: 'contraindication' },
  adverseOutcome: { type: Schema.Types.ObjectId, ref: 'adverseOutcome' },
  study: { type: Schema.Types.ObjectId, ref: 'study' },
  relevantSpecialty: { type: Schema.Types.ObjectId, ref: 'relevantSpecialty' },
  recognizingAuthority: { type: Schema.Types.ObjectId, ref: 'recognizingAuthority' },
  medicineSystem: { type: Schema.Types.ObjectId, ref: 'medicineSystem' },
  guideline: { type: Schema.Types.ObjectId, ref: 'guideline' },
  code: { type: Schema.Types.ObjectId, ref: 'code' },
  url: { type: Schema.Types.ObjectId, ref: 'url' },
  sameAs: { type: Schema.Types.ObjectId, ref: 'sameAs' },
  name: { type: Schema.Types.ObjectId, ref: 'name' },
  image: { type: Schema.Types.ObjectId, ref: 'image' },
  description: { type: Schema.Types.ObjectId, ref: 'description' },
  alternateName: { type: Schema.Types.ObjectId, ref: 'alternateName' },
  additionalType: { type: Schema.Types.ObjectId, ref: 'additionalType' } });
module.exports = mongoose.model('Drug', schema);