var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var schema = new Schema({ toLocation: { type: Schema.Types.ObjectId, ref: 'toLocation' },
  sportsTeam: { type: Schema.Types.ObjectId, ref: 'sportsTeam' },
  sportsEvent: { type: Schema.Types.ObjectId, ref: 'sportsEvent' },
  sportsActivityLocation: { type: Schema.Types.ObjectId, ref: 'sportsActivityLocation' },
  oponent: { type: Schema.Types.ObjectId, ref: 'oponent' },
  fromLocation: { type: Schema.Types.ObjectId, ref: 'fromLocation' },
  exerciseType: { type: Schema.Types.ObjectId, ref: 'exerciseType' },
  exercisePlan: { type: Schema.Types.ObjectId, ref: 'exercisePlan' },
  distance: { type: Schema.Types.ObjectId, ref: 'distance' },
  diet: { type: Schema.Types.ObjectId, ref: 'diet' },
  course: { type: Schema.Types.ObjectId, ref: 'course' },
  event: { type: Schema.Types.ObjectId, ref: 'event' },
  audience: { type: Schema.Types.ObjectId, ref: 'audience' },
  startTime: { type: Schema.Types.ObjectId, ref: 'startTime' },
  result: { type: Schema.Types.ObjectId, ref: 'result' },
  participant: { type: Schema.Types.ObjectId, ref: 'participant' },
  object: { type: Schema.Types.ObjectId, ref: 'object' },
  location: { type: Schema.Types.ObjectId, ref: 'location' },
  instrument: { type: Schema.Types.ObjectId, ref: 'instrument' },
  endTime: { type: Schema.Types.ObjectId, ref: 'endTime' },
  agent: { type: Schema.Types.ObjectId, ref: 'agent' },
  url: { type: Schema.Types.ObjectId, ref: 'url' },
  sameAs: { type: Schema.Types.ObjectId, ref: 'sameAs' },
  name: { type: Schema.Types.ObjectId, ref: 'name' },
  image: { type: Schema.Types.ObjectId, ref: 'image' },
  description: { type: Schema.Types.ObjectId, ref: 'description' },
  alternateName: { type: Schema.Types.ObjectId, ref: 'alternateName' },
  additionalType: { type: Schema.Types.ObjectId, ref: 'additionalType' } });
module.exports = mongoose.model('ExerciseAction', schema);