var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var schema = new Schema({ infectiousAgent: { type: Schema.Types.ObjectId, ref: 'infectiousAgent' },
  infectiousAgentClass: { type: Schema.Types.ObjectId, ref: 'infectiousAgentClass' },
  transmissionMethod: { type: Schema.Types.ObjectId, ref: 'transmissionMethod' },
  associatedAnatomy: { type: Schema.Types.ObjectId, ref: 'associatedAnatomy' },
  cause: { type: Schema.Types.ObjectId, ref: 'cause' },
  differentialDiagnosis: { type: Schema.Types.ObjectId, ref: 'differentialDiagnosis' },
  epidemiology: { type: Schema.Types.ObjectId, ref: 'epidemiology' },
  expectedPrognosis: { type: Schema.Types.ObjectId, ref: 'expectedPrognosis' },
  naturalProgression: { type: Schema.Types.ObjectId, ref: 'naturalProgression' },
  pathophysiology: { type: Schema.Types.ObjectId, ref: 'pathophysiology' },
  possibleComplication: { type: Schema.Types.ObjectId, ref: 'possibleComplication' },
  possibleTreatment: { type: Schema.Types.ObjectId, ref: 'possibleTreatment' },
  primaryPrevention: { type: Schema.Types.ObjectId, ref: 'primaryPrevention' },
  riskFactor: { type: Schema.Types.ObjectId, ref: 'riskFactor' },
  secondaryPrevention: { type: Schema.Types.ObjectId, ref: 'secondaryPrevention' },
  signOrSymptom: { type: Schema.Types.ObjectId, ref: 'signOrSymptom' },
  stage: { type: Schema.Types.ObjectId, ref: 'stage' },
  subtype: { type: Schema.Types.ObjectId, ref: 'subtype' },
  typicalTest: { type: Schema.Types.ObjectId, ref: 'typicalTest' },
  alternateName: { type: Schema.Types.ObjectId, ref: 'alternateName' },
  code: { type: Schema.Types.ObjectId, ref: 'code' },
  guideline: { type: Schema.Types.ObjectId, ref: 'guideline' },
  medicineSystem: { type: Schema.Types.ObjectId, ref: 'medicineSystem' },
  recognizingAuthority: { type: Schema.Types.ObjectId, ref: 'recognizingAuthority' },
  relevantSpecialty: { type: Schema.Types.ObjectId, ref: 'relevantSpecialty' },
  study: { type: Schema.Types.ObjectId, ref: 'study' },
  additionalType: { type: Schema.Types.ObjectId, ref: 'additionalType' },
  alternateName: { type: Schema.Types.ObjectId, ref: 'alternateName' },
  description: { type: Schema.Types.ObjectId, ref: 'description' },
  image: { type: Schema.Types.ObjectId, ref: 'image' },
  name: { type: Schema.Types.ObjectId, ref: 'name' },
  sameAs: { type: Schema.Types.ObjectId, ref: 'sameAs' },
  url: { type: Schema.Types.ObjectId, ref: 'url' },
  potentialAction: { type: Schema.Types.ObjectId, ref: 'potentialAction' } });
module.exports = mongoose.model('InfectiousDisease', schema);