var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var schema = new Schema({ baseSalary: { type: Schema.Types.ObjectId, ref: 'baseSalary' },
  benefits: { type: Schema.Types.ObjectId, ref: 'benefits' },
  datePosted: { type: Schema.Types.ObjectId, ref: 'datePosted' },
  educationRequirements: { type: Schema.Types.ObjectId, ref: 'educationRequirements' },
  employmentType: { type: Schema.Types.ObjectId, ref: 'employmentType' },
  experienceRequirements: { type: Schema.Types.ObjectId, ref: 'experienceRequirements' },
  hiringOrganization: { type: Schema.Types.ObjectId, ref: 'hiringOrganization' },
  incentives: { type: Schema.Types.ObjectId, ref: 'incentives' },
  industry: { type: Schema.Types.ObjectId, ref: 'industry' },
  jobLocation: { type: Schema.Types.ObjectId, ref: 'jobLocation' },
  occupationalCategory: { type: Schema.Types.ObjectId, ref: 'occupationalCategory' },
  qualifications: { type: Schema.Types.ObjectId, ref: 'qualifications' },
  responsibilities: { type: Schema.Types.ObjectId, ref: 'responsibilities' },
  salaryCurrency: { type: Schema.Types.ObjectId, ref: 'salaryCurrency' },
  skills: { type: Schema.Types.ObjectId, ref: 'skills' },
  specialCommitments: { type: Schema.Types.ObjectId, ref: 'specialCommitments' },
  title: { type: Schema.Types.ObjectId, ref: 'title' },
  workHours: { type: Schema.Types.ObjectId, ref: 'workHours' },
  additionalType: { type: Schema.Types.ObjectId, ref: 'additionalType' },
  alternateName: { type: Schema.Types.ObjectId, ref: 'alternateName' },
  description: { type: Schema.Types.ObjectId, ref: 'description' },
  image: { type: Schema.Types.ObjectId, ref: 'image' },
  name: { type: Schema.Types.ObjectId, ref: 'name' },
  sameAs: { type: Schema.Types.ObjectId, ref: 'sameAs' },
  url: { type: Schema.Types.ObjectId, ref: 'url' },
  potentialAction: { type: Schema.Types.ObjectId, ref: 'potentialAction' } });
module.exports = mongoose.model('JobPosting', schema);