var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var schema = new Schema({ acceptedOffer: { type: Schema.Types.ObjectId, ref: 'acceptedOffer' },
  billingAddress: { type: Schema.Types.ObjectId, ref: 'billingAddress' },
  confirmationNumber: { type: Schema.Types.ObjectId, ref: 'confirmationNumber' },
  customer: { type: Schema.Types.ObjectId, ref: 'customer' },
  discount: { type: Schema.Types.ObjectId, ref: 'discount' },
  discountCode: { type: Schema.Types.ObjectId, ref: 'discountCode' },
  discountCurrency: { type: Schema.Types.ObjectId, ref: 'discountCurrency' },
  isGift: { type: Schema.Types.ObjectId, ref: 'isGift' },
  merchant: { type: Schema.Types.ObjectId, ref: 'merchant' },
  orderDate: { type: Schema.Types.ObjectId, ref: 'orderDate' },
  orderedItem: { type: Schema.Types.ObjectId, ref: 'orderedItem' },
  orderNumber: { type: Schema.Types.ObjectId, ref: 'orderNumber' },
  orderStatus: { type: Schema.Types.ObjectId, ref: 'orderStatus' },
  paymentDue: { type: Schema.Types.ObjectId, ref: 'paymentDue' },
  paymentMethod: { type: Schema.Types.ObjectId, ref: 'paymentMethod' },
  paymentMethodId: { type: Schema.Types.ObjectId, ref: 'paymentMethodId' },
  paymentUrl: { type: Schema.Types.ObjectId, ref: 'paymentUrl' },
  additionalType: { type: Schema.Types.ObjectId, ref: 'additionalType' },
  alternateName: { type: Schema.Types.ObjectId, ref: 'alternateName' },
  description: { type: Schema.Types.ObjectId, ref: 'description' },
  image: { type: Schema.Types.ObjectId, ref: 'image' },
  name: { type: Schema.Types.ObjectId, ref: 'name' },
  sameAs: { type: Schema.Types.ObjectId, ref: 'sameAs' },
  url: { type: Schema.Types.ObjectId, ref: 'url' },
  potentialAction: { type: Schema.Types.ObjectId, ref: 'potentialAction' } });
module.exports = mongoose.model('Order', schema);