var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var schema = new Schema({ worksFor: { type: Schema.Types.ObjectId, ref: 'worksFor' },
  workLocation: { type: Schema.Types.ObjectId, ref: 'workLocation' },
  vatID: { type: Schema.Types.ObjectId, ref: 'vatID' },
  telephone: { type: Schema.Types.ObjectId, ref: 'telephone' },
  taxID: { type: Schema.Types.ObjectId, ref: 'taxID' },
  spouse: { type: Schema.Types.ObjectId, ref: 'spouse' },
  siblings: { type: Schema.Types.ObjectId, ref: 'siblings' },
  sibling: { type: Schema.Types.ObjectId, ref: 'sibling' },
  seeks: { type: Schema.Types.ObjectId, ref: 'seeks' },
  relatedTo: { type: Schema.Types.ObjectId, ref: 'relatedTo' },
  performerIn: { type: Schema.Types.ObjectId, ref: 'performerIn' },
  parents: { type: Schema.Types.ObjectId, ref: 'parents' },
  parent: { type: Schema.Types.ObjectId, ref: 'parent' },
  owns: { type: Schema.Types.ObjectId, ref: 'owns' },
  nationality: { type: Schema.Types.ObjectId, ref: 'nationality' },
  naics: { type: Schema.Types.ObjectId, ref: 'naics' },
  memberOf: { type: Schema.Types.ObjectId, ref: 'memberOf' },
  makesOffer: { type: Schema.Types.ObjectId, ref: 'makesOffer' },
  knows: { type: Schema.Types.ObjectId, ref: 'knows' },
  jobTitle: { type: Schema.Types.ObjectId, ref: 'jobTitle' },
  isicV4: { type: Schema.Types.ObjectId, ref: 'isicV4' },
  interactionCount: { type: Schema.Types.ObjectId, ref: 'interactionCount' },
  honorificSuffix: { type: Schema.Types.ObjectId, ref: 'honorificSuffix' },
  honorificPrefix: { type: Schema.Types.ObjectId, ref: 'honorificPrefix' },
  homeLocation: { type: Schema.Types.ObjectId, ref: 'homeLocation' },
  hasPOS: { type: Schema.Types.ObjectId, ref: 'hasPOS' },
  globalLocationNumber: { type: Schema.Types.ObjectId, ref: 'globalLocationNumber' },
  givenName: { type: Schema.Types.ObjectId, ref: 'givenName' },
  gender: { type: Schema.Types.ObjectId, ref: 'gender' },
  follows: { type: Schema.Types.ObjectId, ref: 'follows' },
  faxNumber: { type: Schema.Types.ObjectId, ref: 'faxNumber' },
  familyName: { type: Schema.Types.ObjectId, ref: 'familyName' },
  email: { type: Schema.Types.ObjectId, ref: 'email' },
  duns: { type: Schema.Types.ObjectId, ref: 'duns' },
  deathDate: { type: Schema.Types.ObjectId, ref: 'deathDate' },
  contactPoints: { type: Schema.Types.ObjectId, ref: 'contactPoints' },
  contactPoint: { type: Schema.Types.ObjectId, ref: 'contactPoint' },
  colleagues: { type: Schema.Types.ObjectId, ref: 'colleagues' },
  colleague: { type: Schema.Types.ObjectId, ref: 'colleague' },
  children: { type: Schema.Types.ObjectId, ref: 'children' },
  brand: { type: Schema.Types.ObjectId, ref: 'brand' },
  birthDate: { type: Schema.Types.ObjectId, ref: 'birthDate' },
  awards: { type: Schema.Types.ObjectId, ref: 'awards' },
  award: { type: Schema.Types.ObjectId, ref: 'award' },
  alumniOf: { type: Schema.Types.ObjectId, ref: 'alumniOf' },
  affiliation: { type: Schema.Types.ObjectId, ref: 'affiliation' },
  address: { type: Schema.Types.ObjectId, ref: 'address' },
  additionalName: { type: Schema.Types.ObjectId, ref: 'additionalName' },
  url: { type: Schema.Types.ObjectId, ref: 'url' },
  sameAs: { type: Schema.Types.ObjectId, ref: 'sameAs' },
  name: { type: Schema.Types.ObjectId, ref: 'name' },
  image: { type: Schema.Types.ObjectId, ref: 'image' },
  description: { type: Schema.Types.ObjectId, ref: 'description' },
  alternateName: { type: Schema.Types.ObjectId, ref: 'alternateName' },
  additionalType: { type: Schema.Types.ObjectId, ref: 'additionalType' } });
module.exports = mongoose.model('Person', schema);